// Generated by CoffeeScript 1.10.0
var DTTMain, StartSelector, a, button, div, el, form, h1, h2, h3, h4, img, initialState, input, label, li, option, p, ref, render, select, span, store, strong, trainerLogic, ul;

ref = React.DOM, a = ref.a, button = ref.button, div = ref.div, form = ref.form, img = ref.img, h1 = ref.h1, h2 = ref.h2, h3 = ref.h3, h4 = ref.h4, input = ref.input, label = ref.label, li = ref.li, option = ref.option, p = ref.p, select = ref.select, span = ref.span, strong = ref.strong, ul = ref.ul;

el = React.createElement;

initialState = {
  gameParams: {
    type: 'random',
    min: 5,
    max: 10,
    mins: 5,
    secs: 300
  }
};

trainerLogic = function(state, action) {
  if (state == null) {
    state = initialState;
  }
  return state;
};

store = Redux.createStore(trainerLogic);

StartSelector = React.createClass({
  render: function() {
    return div({}, p({
      className: "lead"
    }, 'The game is not started yet. Select training time and press Start.'), form({
      className: "form-inline",
      onSubmit: this.handleSubmit
    }, div({
      className: "form-group"
    }, label({}, 'Time: '), select({
      className: "form-control",
      defaultValue: this.props.type,
      onChange: this.changeType,
      style: {
        width: 'auto'
      }
    }, option({
      value: 'random'
    }, 'Random time'), option({
      value: 'minutes'
    }, 'Minutes'), option({
      value: 'seconds'
    }, 'Seconds'))), ' ', div({
      className: "form-group"
    }, label({}, 'Min: '), div({
      className: 'input-group'
    }, input({
      type: 'number',
      className: "form-control"
    }), div({
      className: 'input-group-addon'
    }, 'min'))), ' ', div({
      className: "form-group"
    }, label({}, 'Max: '), div({
      className: 'input-group'
    }, input({
      type: 'number',
      className: "form-control"
    }), div({
      className: 'input-group-addon'
    }, 'min'))), ' ', button({
      type: "submit",
      className: "btn btn-primary"
    }, 'Start')));
  }
});

DTTMain = React.createClass({
  render: function() {
    return div({
      className: "container"
    }, h1({}, 'DT Trainer'), this.props.started ? el(Game) : el(StartSelector, this.props.gameParams));
  }
});

render = function() {
  return ReactDOM.render(el(DTTMain, store.getState()), document.getElementById('content'));
};

store.subscribe(render);

render();
