// Generated by CoffeeScript 1.10.0
var Game, TH1Main, a, button, d16, div, form, fullRow, h1, h3, h4, img, input, label, li, option, p, ref, row, select, span, strong, ul;

ref = React.DOM, a = ref.a, button = ref.button, div = ref.div, form = ref.form, img = ref.img, h1 = ref.h1, h3 = ref.h3, h4 = ref.h4, input = ref.input, label = ref.label, li = ref.li, option = ref.option, p = ref.p, select = ref.select, span = ref.span, strong = ref.strong, ul = ref.ul;

row = function(optsOrContent, maybeContent) {
  var content, opts;
  if (maybeContent) {
    content = maybeContent;
    opts = optsOrContent;
  } else {
    content = optsOrContent;
    opts = {};
  }
  return div({
    key: opts.key,
    className: 'row',
    style: {
      marginTop: 20
    }
  }, content);
};

fullRow = function(optsOrContent, maybeContent) {
  var content, opts;
  if (maybeContent) {
    content = maybeContent;
    opts = optsOrContent;
  } else {
    content = optsOrContent;
    opts = {};
  }
  return row(opts, div({
    className: "col-xs-12 " + opts.additionalClass
  }, content));
};

d16 = function() {
  return parseInt(1 + Math.random() * 6);
};

Game = React.createClass({displayName: "Game",
  getInitialState: function() {
    return {
      position: this.randomPosition(),
      nextTask: 0,
      tasks: []
    };
  },
  randomPosition: function() {
    return _.sample(['On the floor, kneeling', 'On the floor, ass on the ground between your legs', 'Neck on border of your bed', 'Sitting in the bathtub', 'Standing']);
  },
  tasks: [['lick on it', 'gag on it 5 times', 'gag on it 10 times', 'swallow it down your throat 5 times', 'swallow it down your throat 10 times', 'gag on it 15 times, then swallow it down your throat 15 times'], ['Very slowly, go deeper and deeper', 'push it down your throat and leave it there for 3 seconds.', 'push it down your throat and leave it there for 6 seconds.', 'Push it in as fast as you can and leave it there for 10 seconds', 'Push it in as fast as you can and leave it there for 15 seconds', 'Push it into your throat and out as fast you can 3 times, repeat it 5 times'], [], ['Play with your spit with both hands', 'I want to see your face full of spit', 'Get all that Spit back into your dirty mouth, after that back into the bowl, slowly', 'Gather all the spit in your hands, then suck it back into your mouth', 'Get all that Spit back into your dirty mouth and swallow it', 'Take all that spit and grease it on your belly, tits and face']],
  randomTask: function(num) {
    var d3, j, ref1, secs;
    if (2 === num) {
      d3 = d16();
      secs = 0;
      for (j = 1, ref1 = d3; 1 <= ref1 ? j <= ref1 : j >= ref1; 1 <= ref1 ? j++ : j--) {
        secs += d16();
      }
      return "Hold your dildo in your throat for " + secs + " seconds.";
    } else {
      return _.sample(this.tasks[num]);
    }
  },
  speak: function(task) {
    if (this.props.speechEnabled) {
      return responsiveVoice.speak(task, "UK English Female", {
        rate: 0.8
      });
    }
  },
  getNextTask: function() {
    var task;
    task = this.randomTask(this.state.nextTask);
    this.speak(task);
    return this.setState({
      nextTask: 1 + this.state.nextTask,
      tasks: this.state.tasks.concat(task)
    });
  },
  render: function() {
    return div({}, fullRow({
      additionalClass: 'xxlead'
    }, span({}, strong({}, 'Position: '), this.state.position)), _.map(this.state.tasks, (function(_this) {
      return function(task, i) {
        return fullRow({
          key: "task" + i
        }, task);
      };
    })(this)), fullRow(this.state.nextTask < this.tasks.length ? button({
      className: "btn btn-primary btn-lg center-block",
      onClick: this.getNextTask
    }, 'Get next task') : span({}, 'Finished!')));
  }
});

TH1Main = React.createClass({displayName: "TH1Main",
  getInitialState: function() {
    return {
      started: false,
      speechEnabled: true
    };
  },
  startAnother: function() {
    return this.setState({
      started: false
    });
  },
  startGame: function() {
    return this.setState({
      started: true
    });
  },
  toggleSpeech: function() {
    return this.setState({
      speechEnabled: !this.state.speechEnabled
    });
  },
  render: function() {
    return div({
      className: "container"
    }, h1({}, 'Throat Heaven 1'), this.renderIntroduction(), this.state.started ? React.createElement(Game, {
      startAnother: this.startAnother,
      speechEnabled: this.state.speechEnabled
    }) : this.renderStartGameButton(), this.renderFooter());
  },
  renderFooter: function() {
    return div({
      className: 'row',
      style: {
        marginTop: 20
      }
    }, div({
      className: "col-xs-4"
    }, label({}, input({
      type: 'checkbox',
      checked: this.state.speechEnabled,
      onChange: this.toggleSpeech
    }), ' Enable speech')), div({
      className: "col-xs-8 pull-right lead"
    }, 'Based on ', a({
      href: 'http://www.getdare.com/bbs/showthread.php?t=176573',
      target: '_blank'
    }, 'Throat Heaven 1 dare')));
  },
  renderStartGameButton: function() {
    return fullRow(button({
      className: "btn btn-primary btn-lg center-block",
      onClick: this.startGame
    }, 'Start a new dare'));
  },
  renderIntroduction: function() {
    return div({
      className: 'panel panel-default'
    }, div({
      className: 'panel-heading'
    }, h3({
      className: 'panel-title'
    }, 'Introduction')), div({
      className: 'panel-body'
    }, p({}, "Get naked. Grab your doubledildo or something that you can swallow."), p({}, "Place a bowl under your face. You will create lots of spit, don't swallow it, the bowl has to be full of your spit."), p({}, "Roll to determine how you must suck the dildo. ")));
  }
});

ReactDOM.render(React.createElement(TH1Main, null), document.getElementById('content'));
