// Generated by CoffeeScript 1.10.0
(function() {
  var Game, OWRMain, StartSelector;

  StartSelector = React.createClass({displayName: "StartSelector",
    getInitialState: function() {
      return {
        value: 0
      };
    },
    handleSubmit: function(e) {
      e.preventDefault();
      return this.props.started(this.state.value);
    },
    handleChange: function(e) {
      return this.setState({
        value: e.target.value
      });
    },
    render: function() {
      var x;
      return React.createElement("div", null, React.createElement("p", {
        "className": "lead"
      }, "The game is not started. To start it select a value for A (target amount of money) and press Start."), React.createElement("form", {
        "className": "form-inline",
        "onSubmit": this.handleSubmit
      }, React.createElement("div", {
        "className": "form-group"
      }, React.createElement("label", null, "A ="), React.createElement("select", {
        "name": 'A',
        "className": "form-control",
        "onChange": this.handleChange
      }, React.createElement("option", {
        "value": 0
      }, "Random"), (function() {
        var i, results;
        results = [];
        for (x = i = 1; i <= 10; x = ++i) {
          results.push(React.createElement("option", {
            "key": x
          }, x));
        }
        return results;
      })())), ' ', React.createElement("button", {
        "type": "submit",
        "className": "btn btn-primary"
      }, "Start")));
    }
  });

  Game = React.createClass({displayName: "Game",
    render: function() {
      return React.createElement("div", null, "Target money: $", this.props.A * 100);
    }
  });

  OWRMain = React.createClass({displayName: "OWRMain",
    getInitialState: function() {
      return {
        started: false
      };
    },
    startGame: function(a) {
      a || (a = parseInt(1 + Math.random() * 10));
      return this.setState({
        started: true,
        A: a
      });
    },
    render: function() {
      return React.createElement("div", {
        "className": "OWRMain container"
      }, React.createElement("h1", null, "OWRMain"), (this.state.started ? React.createElement(Game, {
        "A": this.state.A
      }) : React.createElement(StartSelector, {
        "started": this.startGame
      })));
    }
  });

  ReactDOM.render(React.createElement(OWRMain, null), document.getElementById('content'));

}).call(this);
