// Generated by CoffeeScript 1.10.0
(function() {
  var CommentBox;

  CommentBox = React.createClass({displayName: "CommentBox",
    render: function() {
      return React.createElement("div", {
        "className": "commentBox"
      }, "Hello, world! I am a CommentBox.");
    }
  });

  ReactDOM.render(React.createElement(CommentBox, null), document.getElementById('content'));

}).call(this);
